# Generated by Django 5.0.1 on 2024-01-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.DecimalField(decimal_places=2, max_digits=10)),
                ('draw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('away', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team1_name', models.CharField(max_length=200)),
                ('team2_name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=200, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('team1_name', models.CharField(max_length=200, null=True)),
                ('team2_name', models.CharField(max_length=200, null=True)),
                ('bet_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betapp.betmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
