# Generated by Django 5.0.1 on 2024-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0003_alter_profile_balance_alter_profile_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to='paymentpic'),
        ),
    ]
